pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Start MLflow') {
            steps {
                sh 'cd /workspace && docker compose up -d mlflow'
            }
        }
        stage('Train Model') {
            steps {
                sh 'cd /workspace && docker compose run --rm trainer'
            }
        }
        stage('Stop MLflow') {
            steps {
                sh 'cd /workspace && docker compose down mlflow'
            }
        }
        stage('Test') {
            steps {
                echo 'Model training completed'
            }
        }
    }
}
